[build]
  command = "npm run build"
  functions = "lambda"
  publish="build"

[dev]
  command = "npm run serve"
  port = 3000
  publish = "build"
  functionsPort = 9000

[production]
  command = "npm run build:netlify"
  publish = "build"
